name: Spawn
version: '${project.version}'
main: cn.org.oritention.mc.spawn.Spawn
api-version: 1.16
authors: [ OritentionStudio, GeekKid ]
description: A plugin about spawnpoint settings for minigame servers
website: mc.oritention.org.cn
commands:
  setspawn:
    description: set spawnpoint and write it to the config file
  spawn:
    description: teleport a player to spawnpoint
